name: Tier2
version: 1.6
description: Staff aid/player mode separation.
author: SyntaxNode & zifnab06
website: http://github.com/junctionat/Tier2

main: at.junction.tier2.Tier2
database: true
softdepend: [PermissionsEx, LogBlock]

commands:
  staff:
    description: View a list of staff.
    permission: tier2.list
    usage: /staff
  mode:
    description: Toggle between player and assistance mode.
    permission: tier2.mode
    usage: /mode
  vanish:
    description: Vanish to other players.
    permission: tier2.vanish
    usage: /vanish
  unvanish:
    description: Reappear to other players.
    permission: tier2.vanish
    usage: /unvanish
  modreq:
    description: Submit a help request.
    permission: tier2.req
    usage: /modreq <details>
  check:
    description: Check tickets. Include ID for ticket-specific details.
    permission: tier2.req
    usage: /check <#>
  claim:
    description: Claim a ticket.
    permission: tier2.ticket
    usage: /claim <#>
  tpclaim:
    description: Claim a ticket and teleport to it.
    permission: tier2.ticket
    usage: /tpclaim <#>
  tp-id:
    description: Teleport to a ticket.
    permission: tier2.ticket
    usage: /tp-id <#>
  unclaim:
    description: Unclaim a ticket.
    permission: tier2.ticket
    usage: /unclaim <#>
  done:
    description: Close a ticket.
    permission: tier2.ticket
    usage: /done <#> <message>
  elevate:
    description: Elevate a ticket.
    permission: tier2.ticket
    usage: /elevate <#> <group>
  hide:
    description: Hide yourself from /staff
    permission: tier2.hide
    usage: /hide
  unhide:
    description: Add yourself to /staff
    permission: tier2.hide
    usage: /unhide
  tier2-reload:
    description: Reload Tier2 configuration
    permission: tier2.reload
    usage: /tier2-reload
  supermode:
    description: Put a player into supermode. Must be run from console.
    permission: tier2.superpowers
    usage: /supermode <user> <reason>
permissions:
  tier2.staff:
    description: Staff access.
    default: false
    children:
      tier2.req:
        description: Allow a player to submit a help request.
        default: true
      tier2.list:
        description: Allow a player to view a list of staff.
        default: true
      tier2.ticket:
        description: Allow a player to access staff-side ticket functionality.
        default: op
      tier2.mode:
        description: Allow a player to toggle between player and assistance mode.
        default: false
      tier2.vanish:
        description: Allow a player to vanish / unvanish.
        default: false
        children:
          tier2.vanish.see:
            description: Allow a player to see vanished players.
            default: false
      tier2.hide:
        description: Allow a player to remove themself from the /staff listing
        default: false
  tier2.reload:
    description: Reload Tier2 configuration
    default: op
  tier2.superpowers:
    description: Required to have /supermode used on you
    default: op
